# Generated by Django 4.2 on 2023-04-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0006_remove_recipe_ingredients_and_more"),
        ("users", "0002_alter_user_email_alter_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="saved_recipes",
            field=models.ManyToManyField(to="recipes.recipe"),
        ),
    ]
