source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.7.5"

gem "dotenv-rails"

gem "bootsnap", require: false
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"
gem "rails", "~> 7.0.3", ">= 7.0.3.1"
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem "active_model_serializers", "~> 0.10.12"
gem "bcrypt", "~> 3.1", ">= 3.1.12"
gem "jwt", "~> 2.5"
gem "rack-cors"

gem "cloudinary"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

gem "sneakers", "~> 2.11"
gem "bunny", "~> 2.22"
