# Generated by Django 4.2 on 2023-04-27 23:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('preparation_steps', '0003_alter_preparationstep_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparationstep',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preparationstep',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
