# Generated by Django 4.2 on 2023-04-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparation_steps', '0001_initial'),
        ('recipes', '0003_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation_steps',
            field=models.ManyToManyField(to='preparation_steps.preparationstep'),
        ),
    ]
