# Generated by Django 4.2 on 2023-04-13 19:09

from apps.categories.models import Category
from django.db import migrations

categories = [
    "Bolos e Tortas",
    "Doces e Sobremesas",
    "Tortas Salgadas",
    "Carnes",
    "Aves",
    "Peixes e Frutos do mar",
    "Saladas",
    "Acompanhamentos",
    "Sopas",
    "Massas",
    "Bebidas",
    "Lanches",
    "Sem glúten",
    "Sem lactose",
    "Vegano",
    "Vegetariano",
    "Saudável",
    "Lanches",
    "Estrangeiro",
]


def create_categories(apps, schema_editor):
    for category in categories:
        Category.objects.create(name=category)


def delete_categories(apps, schema_editor):
    Category.objects.filter(name__in=categories).delete


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_alter_category_name"),
    ]

    operations = [migrations.RunPython(create_categories, delete_categories)]
