# Generated by Django 4.2 on 2023-04-12 21:21

import apps.recipes.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_creator'),
        ('ingredients', '0002_alter_ingredient_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(default=apps.recipes.models.Recipe.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
    ]
